# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UtrCli < Formula
  desc "A command line interface for the [Universal Tennis Rating](https://www.myutr.com/) system. This tool allows you to quickly lookup Tennis or PickleBall players and view their match history."
  homepage "https://github.com/lineville/utr-cli"
  version "0.1.1"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lineville/utr-cli/releases/download/v0.1.1/utr-cli_Darwin_x86_64.tar.gz"
      sha256 "2edf2a29608dcc0745b64f5f9afe758cdcb15109a5af37ffe0a2d661dea4c6ba"

      def install
        bin.install "utr-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lineville/utr-cli/releases/download/v0.1.1/utr-cli_Darwin_arm64.tar.gz"
      sha256 "2d8eb8afb80878e20f07d23229a467e8d1de79caa01189258dec5ab325b1dcdf"

      def install
        bin.install "utr-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lineville/utr-cli/releases/download/v0.1.1/utr-cli_Linux_armv6.tar.gz"
      sha256 "a6b5b17b511b205a7212ec692377706be92925f4888677e1ca2fca042b4390a6"

      def install
        bin.install "utr-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lineville/utr-cli/releases/download/v0.1.1/utr-cli_Linux_arm64.tar.gz"
      sha256 "6d4cb7f91bde7718bdf032b338fcfad10b4df9aa9cdad051964aa3b518c4f516"

      def install
        bin.install "utr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lineville/utr-cli/releases/download/v0.1.1/utr-cli_Linux_x86_64.tar.gz"
      sha256 "52a318fc3157d882974f7a1186cdf033e4b79e17305c3effc899fb328f7e9bcc"

      def install
        bin.install "utr-cli"
      end
    end
  end
end
